import { SessionProvider } from 'next-auth/react';
import '../globals.css';
import WompiProvider from '@/components/wompi-provider';
import { auth } from '@/auth';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await auth();

    return (
        <html lang="en">
            <body>
                <SessionProvider session={session}>
                    <WompiProvider>
                        {children}
                    </WompiProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
